title: Cloud Custodian Services
lang: en


remote_theme: jekyll-theme-cayman

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

theme: jekyll-theme-cayman